package co.pyragon.jamoss.compat.ponder;

import co.pyragon.jamoss.compat.ponder.scenes.GasScenes;
import co.pyragon.jamoss.compat.ponder.scenes.ResonatorScenes;
import co.pyragon.jamoss.compat.ponder.scenes.SieveScenes;
import co.pyragon.jamoss.registry.COBlocks;
import com.tterrag.registrate.util.entry.RegistryEntry;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.minecraft.resources.ResourceLocation;

/**
 * Scene ↔ structure map. Structure files are generated by {@code COPonderStructureGen}; the
 * paths here must match {@link COPonderStructures}.
 */
public class COPonderScenes {

	public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
		PonderSceneRegistrationHelper<RegistryEntry<?, ?>> h = helper.withKeyFunction(RegistryEntry::getId);

		h.forComponents(COBlocks.RESONATOR)
			.addStoryBoard(COPonderStructures.RESONATOR, ResonatorScenes::resonator)
			.addStoryBoard(COPonderStructures.RESONATOR, ResonatorScenes::frequency);

		h.forComponents(COBlocks.RESONANCE_CHAMBER)
			.addStoryBoard(COPonderStructures.CHAMBER, ResonatorScenes::chamber)
			.addStoryBoard(COPonderStructures.RESONATOR, ResonatorScenes::frequency);

		h.forComponents(COBlocks.RESONANCE_PUMP)
			.addStoryBoard(COPonderStructures.PUMP, GasScenes::pump);

		h.forComponents(COBlocks.CONDENSER)
			.addStoryBoard(COPonderStructures.CONDENSER, GasScenes::condenser);

		h.forComponents(COBlocks.VENT)
			.addStoryBoard(COPonderStructures.VENT, GasScenes::vent);

		h.forComponents(COBlocks.TUNING_FORK)
			.addStoryBoard(COPonderStructures.TUNING_FORK, ResonatorScenes::tuningFork);

		h.forComponents(COBlocks.CAVITATION_CHAMBER)
			.addStoryBoard(COPonderStructures.ORE_CHAIN, GasScenes::oreChain);

		h.forComponents(COBlocks.RESONANCE_EMITTER, COBlocks.RESONANCE_RECEIVER)
			.addStoryBoard(COPonderStructures.COUPLER, ResonatorScenes::coupler);

		h.forComponents(COBlocks.SONIC_PULVERISER)
			.addStoryBoard(COPonderStructures.PULVERISER, ResonatorScenes::pulveriser);

		h.forComponents(COBlocks.VIBRATING_SIEVE)
			.addStoryBoard(COPonderStructures.SIEVE, SieveScenes::sieve);
	}
}
